In [1]:
!pip install google_play_scraper

Collecting google_play_scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 1.5 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google_play_scraper
Successfully installed google_play_scraper-1.2.7

In [2]:
from google_play_scraper import app
import pandas as pd
import numpy as np

In [3]:
from google_play_scraper import reviews, Sort

result, continuation_token = reviews(
    'com.dts.freefiremax',
    lang='id',
    country='id',
    sort=Sort.NEWEST,   # pakai Sort, bukan sort
    count=2000,
    filter_score_with=None
)

In [4]:
df_busu = pd.DataFrame(np.array(result),columns=['review'])
df_busu = df_busu.join(pd.DataFrame(df_busu.pop('review').tolist()))
df_busu.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,0c1c02e4-032d-4fa8-9fda-f066ee144355,IBRAHIM ANGKAT SOURAYA 1102,https://play-lh.googleusercontent.com/a-/ALV-U...,sangat baik,5,0,2.115.1,2025-10-05 08:37:31,None,None,2.115.1
1,0baf462f-8d95-488c-a14c-6bf7890ff535,Rara Putry,https://play-lh.googleusercontent.com/a-/ALV-U...,seru,5,0,2.114.1,2025-10-05 08:37:11,None,None,2.114.1
2,99aaf1e4-bab7-48ec-9fd7-3b4f1496948b,Andhit Naufal,https://play-lh.googleusercontent.com/a/ACg8oc...,minta diamond dong,5,0,2.114.1,2025-10-05 08:37:02,None,None,2.114.1
3,89423b57-da8f-4d3b-b027-989c5e86ace8,Risma Saputri,https://play-lh.googleusercontent.com/a/ACg8oc...,bagus,4,0,2.114.1,2025-10-05 08:33:00,None,None,2.114.1
4,1b350eee-29be-4493-9ce9-11675f158ae7,Aman Aman,https://play-lh.googleusercontent.com/a/ACg8oc...,mantap,5,0,2.114.1,2025-10-05 08:31:18,None,None,2.114.1

In [5]:
len(df_busu.index)

2000

In [6]:
df_busu[['userName', 'score', 'at', 'content']].head()

                      userName  score                  at             content
0  IBRAHIM ANGKAT SOURAYA 1102      5 2025-10-05 08:37:31         sangat baik
1                   Rara Putry      5 2025-10-05 08:37:11                seru
2                Andhit Naufal      5 2025-10-05 08:37:02  minta diamond dong
3                Risma Saputri      4 2025-10-05 08:33:00               bagus
4                    Aman Aman      5 2025-10-05 08:31:18              mantap

In [7]:
my_df = df_busu[['userName', 'score', 'at', 'content']]

In [8]:
my_df.to_csv("scraperdata_freefirereviews.csv", index = False)

CASE FOLDING

In [10]:
import pandas as pd

# Baca file CSV
df = pd.read_csv("scraperdata_freefirereviews.csv")

# Tampilkan kolom yang ada
print("Kolom tersedia:", df.columns)

# Misalnya kolom review ada di 'content', lakukan case folding
df['content_casefold'] = df['content'].astype(str).str.lower()

# Simpan hasilnya ke file baru
output_path = "freefire_reviews_casefold.csv"
df.to_csv(output_path, index=False)

print(f"Case folding selesai. File hasil disimpan di {output_path}")

Kolom tersedia: Index(['userName', 'score', 'at', 'content'], dtype='object')
Case folding selesai. File hasil disimpan di freefire_reviews_casefold.csv